### ISSUE TITLE
Troubles cloning project

### ISSUE THREAD

**Issue by valkyrienyanko** [DAPOTTIS/godot-game#3]
![Untitled](https://github.com/DAPOTTIS/godot-game/assets/6277739/06e267d4-eff2-468a-9029-c98234d4399d)

**Comment by DAPOTTIS** [comment]
Hey, I'll get back to you in a few days when I'm back home from vacation so I can help out.

**Comment by DAPOTTIS** [comment]
@valkyrienyanko Hey, I just pushed a commit to remove a ton of those useless files. Try cloning now.

**Comment by valkyrienyanko** [comment]
Thanks it works now, I created PR https://github.com/DAPOTTIS/godot-game/pull/4
